from datetime import datetime

def get_analysis_prompt(project_path: str, focus_areas: list[str] = None) -> str:
    """
    Generate the analysis prompt for CodeScope.
    
    This prompt instructs the agent to analyze code for technical debt
    while being appropriately cautious about false positives.
    """
    
    focus_section = ""
    if focus_areas:
        focus_section = f"""
**FOCUS AREAS:** Pay special attention to:
{chr(10).join(f'- {area}' for area in focus_areas)}
"""
    
    return f'''Analyze the codebase at the current directory for technical debt and code quality issues.

**DATE:** {datetime.now().strftime("%Y-%m-%d")}
**PROJECT:** {project_path}
{focus_section}

** EXECUTION RULES:**
- Execute ALL tools silently (no intermediate text responses)
- Explore the codebase structure FIRST using list_directory and read_file
- After analysis, write the report file, THEN provide a summary
- If you respond with text before writing the file, the loop stops!

** WHAT TO LOOK FOR:**

1. **High Confidence Issues** (likely safe to address):
   - Unused imports at the top of files
   - Variables assigned but never used
   - Empty files or placeholder files
   - Duplicate imports

2. **Medium Confidence Issues** (review recommended):
   - Functions/classes with no apparent callers
   - Large blocks of commented-out code (5+ lines)
   - Old TODO/FIXME comments
   - Files not imported anywhere

3. **Low Confidence Issues** (investigate when time permits):
   - Potential code duplication
   - Overly complex functions
   - Inconsistent naming conventions
   - Missing docstrings

**ANALYSIS STEPS:**

1. First, use `list_directory` to see the project structure
2. Read key files with `read_file` to understand the codebase
3. Look for the patterns described above
4. Before flagging something as "unused", consider:
   - It might be called dynamically
   - It might be exported for external use
   - It might be intentionally kept for reference

**OUTPUT:**

After your analysis, create a Markdown report file with this structure:
```markdown
# CodeScope Analysis Report

**Project:** [name]
**Analyzed:** [date]
**Files Reviewed:** [count]

## Summary

[2-3 sentence overview]

## High Confidence Issues

[List each with file:line and explanation]

## Medium Confidence Issues

[List each with file:line and explanation]

## Low Confidence Issues

[List each with file:line and explanation]

## Statistics

- Unused imports: [count]
- TODO/FIXME comments: [count]
- Commented code blocks: [count]
- Potential dead code: [count]

## Top Recommendations

1. [Most important fix]
2. [Second priority]
3. [Third priority]

---
*Generated by CodeScope*
```

Use `write_file` to save as `codescope_report.md` in the current directory.

**BEGIN ANALYSIS NOW.**
'''