from datetime import datetime

# language-specific patterns to look for
LANGUAGE_PATTERNS = {
    "python": [
        "Bare except clauses (except: without exception type)",
        "Mutable default arguments (def func(items=[]))",
        "print() statements that should use logging",
        "String concatenation in loops (use join instead)",
        "Using type() instead of isinstance()",
    ],
    "javascript": [
        "console.log statements left in code",
        "var instead of let/const",
        "Callback hell (deeply nested callbacks)",
        "== instead of === for comparison",
        "Missing error handling in promises",
    ],
    "typescript": [
        "Use of 'any' type",
        "Missing return types on functions",
        "Non-null assertions (!) overuse",
    ],
    "java": [
        "Empty catch blocks",
        "Raw types instead of generics",
        "Public fields that should be private",
    ],
}

# generate language-specific hints
def get_language_hints(extensions: list[str]) -> str:
    # map extensions to languages
    ext_to_lang = {
        ".py": "python",
        ".js": "javascript",
        ".jsx": "javascript",
        ".ts": "typescript",
        ".tsx": "typescript",
        ".java": "java",
    }
    
    # find which languages are in the project
    languages = set()
    for ext in extensions:
        if ext in ext_to_lang:
            languages.add(ext_to_lang[ext])
    
    if not languages:
        return ""
    
    # build the hints section
    hints = "\n**LANGUAGE-SPECIFIC ISSUES TO CHECK:**\n"
    
    for lang in languages:
        if lang in LANGUAGE_PATTERNS:
            hints += f"\n*{lang.title()}:*\n"
            for pattern in LANGUAGE_PATTERNS[lang]:
                hints += f"   - {pattern}\n"
    
    return hints

# generate the analysis prompt
def get_analysis_prompt(project_path: str, focus_areas: list[str] = None, extensions: list[str] = None) -> str:
    """
    Generate the analysis prompt for CodeScope.
    
    This prompt instructs the agent to analyze code for technical debt
    while being appropriately cautious about false positives.
    """
    
    focus_section = ""
    if focus_areas:
        focus_section = f"""
**FOCUS AREAS:** Pay special attention to:
{chr(10).join(f'- {area}' for area in focus_areas)}
"""
    # Generate language-specific hints based on detected file types
    language_hints = ""
    if extensions:
        language_hints = get_language_hints(extensions)
    
    return f'''Analyze the codebase at the current directory for technical debt and code quality issues.

**DATE:** {datetime.now().strftime("%Y-%m-%d")}
**PROJECT:** {project_path}
{focus_section}


** EXECUTION RULES:**
- Execute ALL tools silently (no intermediate text responses)
- Explore the codebase structure FIRST using list_directory and read_file
- After analysis, write the report file, THEN provide a summary
- If you respond with text before writing the file, the loop stops!

** WHAT TO LOOK FOR:**

1. **High Confidence Issues** (likely safe to address):
   - Unused imports at the top of files
   - Variables assigned but never used
   - Empty files or placeholder files
   - Duplicate imports

2. **Medium Confidence Issues** (review recommended):
   - Functions/classes with no apparent callers
   - Large blocks of commented-out code (5+ lines)
   - Old TODO/FIXME comments
   - Files not imported anywhere

3. **Low Confidence Issues** (investigate when time permits):
   - Potential code duplication
   - Overly complex functions
   - Inconsistent naming conventions
   - Missing docstrings
{language_hints}

**ANALYSIS STEPS:**

1. First, use `list_directory` to see the project structure
2. Read key files with `read_file` to understand the codebase
3. Look for the patterns described above
4. Before flagging something as "unused", consider:
   - It might be called dynamically
   - It might be exported for external use
   - It might be intentionally kept for reference

**OUTPUT:**

After your analysis, create a Markdown report file with this structure:
```markdown
# CodeScope Analysis Report

**Project:** [name]
**Analyzed:** [date]
**Files Reviewed:** [count]

## Summary

[2-3 sentence overview]

## High Confidence Issues

[List each with file:line and explanation]

## Medium Confidence Issues

[List each with file:line and explanation]

## Low Confidence Issues

[List each with file:line and explanation]

{'''
## Language-Specific Issues

[List any language-specific problems found]
''' if language_hints else ""}

## Statistics

- Unused imports: [count]
- TODO/FIXME comments: [count]
- Commented code blocks: [count]
- Potential dead code: [count]
- Language-specific issues: [count]

## Top Recommendations

1. [Most important fix]
2. [Second priority]
3. [Third priority]

---
*Generated by CodeScope*
```

Use `write_file` to save as `codescope_report.md` in the current directory.

**BEGIN ANALYSIS NOW.**
'''