import re
import shutil
from datetime import datetime
from pathlib import Path

from .config import REPORTS_DIR

# func to copy generated report to reports dir
def save_report(source_path: str, project_name: str = None) -> dict:
    source = Path(source_path)
    
    if not source.exists():
        return {"error": f"Report not found: {source_path}"}
    
    # create reports directory
    REPORTS_DIR.mkdir(exist_ok=True)
    
    # generate filename
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    name = project_name or source.parent.name
    safe_name = re.sub(r'[^\w\-]', '_', name)
    
    # copy markdown report
    md_dest = REPORTS_DIR / f"codescope_{safe_name}_{timestamp}.md"
    shutil.copy(source, md_dest)
    
    # also generate HTML version
    html_dest = REPORTS_DIR / f"codescope_{safe_name}_{timestamp}.html"
    html_content = markdown_to_html(source.read_text(), name)
    html_dest.write_text(html_content)
    
    return {
        "markdown": str(md_dest),
        "html": str(html_dest),
    }

# convert markdown report to styled HTML
def markdown_to_html(markdown_content: str, title: str = "CodeScope Report") -> str:
    html_body = markdown_content
    
    # convert headers
    html_body = re.sub(r'^### (.+)$', r'<h3>\1</h3>', html_body, flags=re.MULTILINE)
    html_body = re.sub(r'^## (.+)$', r'<h2>\1</h2>', html_body, flags=re.MULTILINE)
    html_body = re.sub(r'^# (.+)$', r'<h1>\1</h1>', html_body, flags=re.MULTILINE)
    
    # convert bold
    html_body = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html_body)
    
    # convert inline code
    html_body = re.sub(r'`([^`]+)`', r'<code>\1</code>', html_body)
    
    # convert bullet points
    html_body = re.sub(r'^- (.+)$', r'<li>\1</li>', html_body, flags=re.MULTILINE)
    
    # wrap lists
    html_body = re.sub(r'(<li>.*</li>\n)+', r'<ul>\g<0></ul>', html_body)
    
    # convert line breaks to paragraphs
    paragraphs = html_body.split('\n\n')
    html_body = '\n'.join(f'<p>{p}</p>' if not p.startswith('<') else p for p in paragraphs)
    
    return f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        :root {{
            --bg: #0d1117;
            --bg-secondary: #161b22;
            --text: #e6edf3;
            --text-secondary: #8b949e;
            --accent: #58a6ff;
            --red: #f85149;
            --yellow: #d29922;
            --green: #3fb950;
            --border: #30363d;
        }}
        
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
            background: var(--bg);
            color: var(--text);
            line-height: 1.6;
            padding: 2rem;
            max-width: 900px;
            margin: 0 auto;
        }}
        
        h1 {{
            color: var(--accent);
            border-bottom: 2px solid var(--border);
            padding-bottom: 0.5rem;
            margin-bottom: 1.5rem;
        }}
        
        h2 {{
            color: var(--text);
            margin-top: 2rem;
            margin-bottom: 1rem;
        }}
        
        h3 {{
            color: var(--text-secondary);
            margin-top: 1.5rem;
            margin-bottom: 0.5rem;
        }}
        
        p {{
            margin-bottom: 1rem;
        }}
        
        code {{
            background: var(--bg-secondary);
            padding: 0.2rem 0.4rem;
            border-radius: 4px;
            font-family: 'SF Mono', Consolas, monospace;
            font-size: 0.9em;
        }}
        
        ul {{
            margin: 1rem 0;
            padding-left: 1.5rem;
        }}
        
        li {{
            margin-bottom: 0.5rem;
        }}
        
        strong {{
            color: var(--accent);
        }}
        
        /* Emoji styling for confidence levels */
        h2:has(+ ul li:first-child) {{
            display: flex;
            align-items: center;
            gap: 0.5rem;
        }}
    </style>
</head>
<body>
    {html_body}
    <footer style="margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border); color: var(--text-secondary); font-size: 0.9rem;">
        Generated by <a href="https://github.com/jpmusenge/codescope" style="color: var(--accent);">CodeScope</a>
    </footer>
</body>
</html>'''